### ISSUE TITLE
resultados simulações feitas por Melina

### ISSUE THREAD

**Issue by melina-leite** [ecovirt/EcoVirtual#10]
Oi Alê, como você pediu, mando abaixo os comentários das simulações que eu fiz nas funções do EcoVirtual, e incluo os comentários que você já havia feito por email:

1- popExp: fiz uns testes e vi que quanto maior o tmax, menor é o lambda que consegue rodar a função, ou seja, não consigo chegar ao lambda máximo permitido (5):

tmax    =1000  
N0= 1000  
lambda=2.02 
intt = qualquer 
erro    =  independente no intt, quando usamos essa combinação de tmax e N0, a partir do lambda 2.02 dá a mensagem de erro: RcmdrMsg: [21] ERRO:
RcmdrMsg+ 'to' cannot be NA, NaN or infinite

tmax    =500  
N0= 1000  
lambda=4.08 
intt = qualquer 
erro    = mesmo erro de acima.

tmax    =5000  
N0= 1000  
lambda= 1.16  
intt = qualquer 
erro    = mesmo erro de acima.

tmax    =100  
N0= 1000  
lambda= qualquer
intt = qualquer 
erro    = sem erro roda instantaenamente

tmax    =437
N0= 1000  
lambda= 5  
intt = qualquer 
erro    = para que a função rode no lambda=5, o tmax não pode ultrapassar 436

tmax    =439
N0= 10
lambda= 5  
intt = qualquer 
erro    = variar o N0 muda um pouco essa relação mas nem tanto.

R ALE: AQUI O  PROBLEMA AQUI É A PRECISÃO  NUMÉRICA DA MÁQUINA, QUANDO USAMOS O VALOR DE Tmax e N0 = 1000 e lambda =2 o valor final é de 1e+304 e a precisão do R é 2e+308.
 VOU TENTAR COLOCAR UMA MENSAGEM DE ERRO

2 - estEnv dá o mesmo problema de popExp entre o tmax e lambda.
R ALE: MESMO

3 - metaCi - sugestão: o coeficiente de colonização também poderia ser uma barra, como acontece para outros argumentos com valores entre 0 e 1 em metapopulações (ex: coef. extinção em metaEr)
R ALE: AQUI ACHO QUE TEMOS QUE FAZER AO CONTRÁRIO. AS PROBABILIDADES ESTÃO LIMITADAS ENTRE 0-1, OS COEFICIENTES NÃO. COMO OS MODELOS SÃO LINEARES AS RELAÇÕES PODEM LEVAR A UMA PROBABILIDADE IRREAL (>1 OU <0). VOU AJUSTAR TUDO ISSO, USANDO DISTRIBUIÇÕES COMBINADAS (IF P>1 {P=1})
HÁ OUTRO PROBLEMA! AS SIMULAÇÕES NESSES CASOS (PI>1) E/OU (PE>1) , MESMO QUE AJUSTADAS A 1 APRESENTAM EQUILÍBRIOS DIFERENTES DO  ESTIMADO PELOS MODELOS DETERMINÍSTICOS. 1. AS TAXAS SÃO CORRIGIDAS; 2. AS COLONIZAÇÕES E EXTINÇÕES NÃO SÃO INSTANTÂNEAS; 3 O NÚMERO DE MANCHAS É FINITO!

4 - metaCiEr - o botão aplicar fecha a janela (como se fosse o Ok).

5 - regNicho - reparei que as cores nas imagens de ocupação das manchas não tem legenda e também não tem as mesmas cores do gráfico de resultado (que tem legenda). seria bom colocar legenda nas imagens das manchas? ou então padronizar as cores para aproveitar a legenda do gráfico resultado?

**Comment by adalardo** [comment]
All issues described where corrected! Closing...
