### ISSUE TITLE
Imports explicitos

### ISSUE THREAD

**Issue by andrechalom** [ecovirt/EcoVirtual#3]
Segue instrução da lista r-devel:
    \* 'R CMD check --as-cran' now checks code usage (via 'codetools')
      with only the base package attached, so that functions from
      default packages other than base which are used in the package
      code but not imported are reported as undefined globals.

Na URL https://cran.r-project.org/web/checks/check_results_EcoVirtual.html é possível ver que o pacote EcoVirtual ainda não implementou essas mudanças:

```
Consider adding
 importFrom("grDevices", "colorRamp", "colorRampPalette", "dev.new",
 "rainbow", "rgb")
 importFrom("graphics", "abline", "axis", "curve", "grid", "image",
 "layout", "legend", "lines", "matplot", "mtext", "par",
 "plot", "points", "polygon", "segments", "text", "title")
 importFrom("stats", "coef", "lm", "na.omit", "rexp", "rlnorm", "sd",
 "time")
 importFrom("utils", "stack")
to your NAMESPACE. 
```

**Comment by adalardo** [comment]
incorporada
